#redis?????
spring:
  redis:
    host: 192.168.198.138
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  #Redis?????????
  #Redis?????????0
  #??????
  #????????(??????????)
  #??????????????????
  #??????????
  #??????????


  lettuce:
  pool.min-idle: 0
  #配置中文编码格式
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
    force: true
  encoding:
    charset: UTF-8
    enabled: true
    #下面这个静态资源访问前缀加上会导致/默认访问index.html功能失效
  #  mvc:
  #    static-path-pattern: /static
  resources:
    static-locations: [classpath:/templates/]
people:
  name: xiaoming
  sex: man
  server:
    port: 8888
